server:
  port: 8081

spring:
  application:
    name: E-Commerce Application
  datasource:
    url: jdbc:postgresql://localhost:5432/E-Commerce
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
